const COLLABOLANCER_MODULE_ID = 1000;
const COLLABOLANCER_REGISTER_ACCOUNT_ASSET_ID = 1;
const COLLABOLANCER_POST_PROJECT_ASSET_ID = 2;
const COLLABOLANCER_POST_PROPOSAL_ASSET_ID = 3;
const COLLABOLANCER_JOIN_TEAM_ASSET_ID = 4;
const COLLABOLANCER_START_WORK_ASSET_ID = 5;
const COLLABOLANCER_SUBMIT_CONTRIBUTION_ASSET_ID = 6;
const COLLABOLANCER_REJECT_CONTRIBUTION_ASSET_ID = 7;
const COLLABOLANCER_SUBMIT_SUBMISSION_ASSET_ID = 8;
const COLLABOLANCER_REJECT_SUBMISSION_ASSET_ID = 9;
const COLLABOLANCER_FINISH_PROJECT_ASSET_ID = 10;
const COLLABOLANCER_TERMINATE_PROJECT_ASSET_ID = 11;
const COLLABOLANCER_CANCEL_PROJECT_ASSET_ID = 12;
const COLLABOLANCER_OPEN_DISPUTE_ASSET_ID = 13;
const COLLABOLANCER_VOTE_DISPUTE_ASSET_ID = 14;
const COLLABOLANCER_CLOSE_DISPUTE_ASSET_ID = 15;
const COLLABOLANCER_CLAIM_PRIZE_ASSET_ID = 16;

module.exports = {
  COLLABOLANCER_MODULE_ID,
  COLLABOLANCER_REGISTER_ACCOUNT_ASSET_ID,
  COLLABOLANCER_POST_PROJECT_ASSET_ID,
  COLLABOLANCER_POST_PROPOSAL_ASSET_ID,
  COLLABOLANCER_JOIN_TEAM_ASSET_ID,
  COLLABOLANCER_START_WORK_ASSET_ID,
  COLLABOLANCER_SUBMIT_CONTRIBUTION_ASSET_ID,
  COLLABOLANCER_REJECT_CONTRIBUTION_ASSET_ID,
  COLLABOLANCER_SUBMIT_SUBMISSION_ASSET_ID,
  COLLABOLANCER_REJECT_SUBMISSION_ASSET_ID,
  COLLABOLANCER_FINISH_PROJECT_ASSET_ID,
  COLLABOLANCER_TERMINATE_PROJECT_ASSET_ID,
  COLLABOLANCER_CANCEL_PROJECT_ASSET_ID,
  COLLABOLANCER_OPEN_DISPUTE_ASSET_ID,
  COLLABOLANCER_VOTE_DISPUTE_ASSET_ID,
  COLLABOLANCER_CLOSE_DISPUTE_ASSET_ID,
  COLLABOLANCER_CLAIM_PRIZE_ASSET_ID,
};
