const MISCELLANEOUS = {
  FILE_MAXSIZE: 1500000,
  EMPLOYER_COMMITMENT_PERMYRIAD: 1000,
  LEADER_COMMITMENT_PERMYRIAD: 1000,
  TEAM_COMMITMENT_PERMYRIAD: 500,
  LEADER_NOTSELECTED_PINALTY_PERMYRIAD: 100,
  EMPLOYER_REJECTION_PINALTY_PERMYRIAD: 1000,
  EMPLOYER_CASHBACK_PERMYRIAD: 0,
  CASHBACK_DEFLATIONARY_MILESTONE: [
    2073600,
    4147200,
    6220800,
    8294400,
    10368000,
  ],
  TEAM_CASHBACK_PERMYRIAD: 10,
  LEADER_CASHBACK_PERMYRIAD: 2,
  DISPUTE_VOTE_FEE_PERMYRIAD: 100,
  DISPUTE_SEIZURE_PERMYRIAD: 10000,
  DISPUTE_MAXIMAL_OPEN_PERIOD: 3,
  DISPUTE_FREEZEDFEE_PINALTY_TOBE_SHARED_PERMYRIAD: 0,
  FUND_FREEZED_PERIOD: 86400,
  DISPUTE_CLOSED_CANBECLOSEDON_MULTIPLIER: 0.1,
  SUBMIT_TO_TERMINATE_MIN_PERIOD: 259200,
  MINIMAL_PROPOSAL_PROJECT_MAXTIME_DIFF: 1,
  DISTRIBUTION: {
    ALL_EQUAL: "all-equal",
    LEADER_FIRST: "leader-first",
  },
  DISPUTE_TYPE: {
    LEADER_VS_EMPLOYER: "leader-vs-employer",
    TEAM_VS_LEADER: "team-vs-leader",
  },
};

module.exports = MISCELLANEOUS;
